baseURL = "https://cristianrohr.xyz"
defaultContentLanguage = "en"
languageCode = "en"

title = "Cristian Rohr"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true


[params]
  # URL for the avatar on homepage
  avatarURL = "/images/IMG_20181116_114106.jpg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-m"

  # Description to display on homepage
  description = "Generative artist. Bioinformatian. Data Scientist."

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["generativeart", "art", "generative", "creativecoding", "genartclub", "p5js", "rtistry"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)


  # Footer text
  footer = "Cristian rohr"

  socialIcons = [
      {name = "twitter", url = "https://twitter.com/cristianrohr"},
      {name = "linkedin", url = "https://www.linkedin.com/in/cristianrohrbio/"},
      {name = "instagram", url = "https://www.instagram.com/cristianrohr.art/"},
      {name = "github", url = "https://github.com/cristianrohr"},
      {name = "google", url = "https://scholar.google.com/citations?user=hyLMQvAAAAAJ&hl=es"},
    ]

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"

    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    name = "Art Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Art Gallery"
    url = "https://art.cristianrohr.xyz/"
    weight = 3

  [[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 5
